fix expected fail

diff --git a/.github/workflows/test-workflows.yaml b/.github/workflows/test-workflows.yaml
--- a/.github/workflows/test-workflows.yaml
+++ b/.github/workflows/test-workflows.yaml
@@ -27,7 +27,7 @@ jobs:
     uses: ./.github/workflows/lint.yaml
     with:
       head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
-      paths: '[".github/custard/test/node/lint-pass"]'
+      paths: '[".github/custard/test/node/lint-fail"]'
       continue-on-error: true
 
   check-expected-fails:
@@ -36,4 +36,6 @@ jobs:
     steps:
       - name: Check lint-fail-node (status=${{ needs.lint-fail-node.outputs.status }})
         if: ${{ needs.lint-fail-node.outputs.status != 'failure' }}
-        run: exit 1
+        run: |
+          echo "Expected this job fail."
+          exit 1
